# Generated by Django 4.1 on 2022-10-19 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto4', '0002_avatar_rename_so_sistemas_delete_desarrollo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'Avatar', 'verbose_name_plural': 'Avatares'},
        ),
        migrations.CreateModel(
            name='ImagenServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servers')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProyecto4.server')),
            ],
        ),
    ]
