# Generated by Django 4.1 on 2022-10-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto4', '0003_alter_avatar_options_imagenserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servers'),
        ),
    ]
