# Generated by Django 4.1 on 2022-10-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto4', '0006_server_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenserver',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='AppProyecto4.server'),
        ),
    ]
